services:
  vitereactshadcnts:
    image: vitereactshadcnts
    build:
      context: c-2043-main
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
